{{- if and .Values.persistence.plugins.enabled (eq .Values.persistence.plugins.storageClass "-") -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mattermost-team-edition.fullname" . }}-plugins
  labels:
    app.kubernetes.io/name: {{ include "mattermost-team-edition.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "mattermost-team-edition.chart" . }}
  annotations:
  {{- range $key, $value := .Values.persistence.plugins.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  capacity:
    storage: {{ .Values.persistence.plugins.size | quote }}
  accessModes:
  - {{ .Values.persistence.plugins.accessMode | quote }}
  hostPath:
    path: {{ .Values.persistence.plugins.localPath | quote }}
  storageClassName: ""
{{- end }}